// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxGEcHgQyMSbm3VTFNE4XMpFDNIO6ePKA',
    appId: '1:546899653756:web:f29005fde020f90c3285f9',
    messagingSenderId: '546899653756',
    projectId: 'tickoff-app-2025',
    authDomain: 'tickoff-app-2025.firebaseapp.com',
    storageBucket: 'tickoff-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDonCaRc69oPlgPOMK7iCIN3SyXxbJ5O7s',
    appId: '1:546899653756:android:ba6c4721ff8892b63285f9',
    messagingSenderId: '546899653756',
    projectId: 'tickoff-app-2025',
    storageBucket: 'tickoff-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgAtNJRggk0hhppiPdNThdDr2sFJbYlyw',
    appId: '1:546899653756:ios:057c37706a35f40d3285f9',
    messagingSenderId: '546899653756',
    projectId: 'tickoff-app-2025',
    storageBucket: 'tickoff-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.tickoff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgAtNJRggk0hhppiPdNThdDr2sFJbYlyw',
    appId: '1:546899653756:ios:057c37706a35f40d3285f9',
    messagingSenderId: '546899653756',
    projectId: 'tickoff-app-2025',
    storageBucket: 'tickoff-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.tickoff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxGEcHgQyMSbm3VTFNE4XMpFDNIO6ePKA',
    appId: '1:546899653756:web:9b2f771115ea2af13285f9',
    messagingSenderId: '546899653756',
    projectId: 'tickoff-app-2025',
    authDomain: 'tickoff-app-2025.firebaseapp.com',
    storageBucket: 'tickoff-app-2025.firebasestorage.app',
  );
}
